### ISSUE TITLE
Proposal: Add higher level `mux` to `coreutils`

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/coreutils#8]
When working with various types of clients (http, sql,...) they usually manage connections transparently. Meaning that they try to be smart about pooling connections and fixing interrupted connections. I think it would be useful to have a higher level `mux` in `coreutils` which behaves similarly.

Essentially when a `renterd` instance has 50 contracts I'd like to be able to create one `mux` for each and not have to worry about them ever again. They would try to keep the TCP connection alive for a while and if the connection breaks due to being inactive for too long, they would establish a new one implicitly on the next call to `NewStream`.

**Comment by ChrisSchinnerl** [comment]
The reason why I'd like to have that in `coreutils` is mostly reusability. e.g. `explored` might also be interested in that and I'm generally not a fan of cross-importing any of the larger repositories containing our "deliverables" (hostd, walletd, renterd, explored)

**Comment by lukechampine** [comment]
My general stance on reuse here is:
1) Implement it locally.
2) If it seems like another repo needs it, copy it.
3) Maintain both copies for a while. Do they converge, or diverge?
4) If they converge, move the implementation to `coreutils`.

In this case specifically, we're at step 1; we don't yet have another repo that needs this thing, so it should live in `renterd` for now.
